name: sampv1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.10.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_screenutil: ^4.0.3+2
  flutter_webrtc: ^0.5.8
  webview_flutter: ^1.0.7
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  location: ^3.2.4
  flare_flutter: ^2.0.6
  package_info: ^0.4.3+4
  effective_dart: ^1.3.1
  bubble: ^1.1.9+1
  lint: ^1.5.3
  path: ^1.8.0
  moor: ^3.4.0
  moor_generator: ^4.1.0
  firebase_ml_vision: ^0.11.0
  share: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700